INSERT INTO DivisionAdministrativa1 VALUES (1, 'San José')
INSERT INTO DivisionAdministrativa1 VALUES (2, 'Alajuela')
INSERT INTO DivisionAdministrativa1 VALUES (3, 'Cartago')
INSERT INTO DivisionAdministrativa1 VALUES (4, 'Heredia')
INSERT INTO DivisionAdministrativa1 VALUES (5, 'Guanacaste')
INSERT INTO DivisionAdministrativa1 VALUES (6, 'Puntarenas')
INSERT INTO DivisionAdministrativa1 VALUES (7, 'Limón')

INSERT INTO DivisionAdministrativa2 VALUES (8, 1, 'San José')
INSERT INTO DivisionAdministrativa2 VALUES (9, 1, 'Escazú')
INSERT INTO DivisionAdministrativa2 VALUES (10, 1, 'Desamparados')
INSERT INTO DivisionAdministrativa2 VALUES (11, 1, 'Puriscal')
INSERT INTO DivisionAdministrativa2 VALUES (12, 1, 'Tarrazú')
INSERT INTO DivisionAdministrativa2 VALUES (13, 1, 'Aserrí')
INSERT INTO DivisionAdministrativa2 VALUES (14, 1, 'Mora')
INSERT INTO DivisionAdministrativa2 VALUES (15, 1, 'Goicoechea')
INSERT INTO DivisionAdministrativa2 VALUES (16, 1, 'Santa Ana')
INSERT INTO DivisionAdministrativa2 VALUES (17, 1, 'Alajuelita')
INSERT INTO DivisionAdministrativa2 VALUES (18, 1, 'Vásquez de Coronado')
INSERT INTO DivisionAdministrativa2 VALUES (19, 1, 'Acosta')
INSERT INTO DivisionAdministrativa2 VALUES (20, 1, 'Tibás')
INSERT INTO DivisionAdministrativa2 VALUES (21, 1, 'Moravia')
INSERT INTO DivisionAdministrativa2 VALUES (22, 1, 'Montes de Oca')
INSERT INTO DivisionAdministrativa2 VALUES (23, 1, 'Turrubares')
INSERT INTO DivisionAdministrativa2 VALUES (24, 1, 'Dota')
INSERT INTO DivisionAdministrativa2 VALUES (25, 1, 'Curridabat')
INSERT INTO DivisionAdministrativa2 VALUES (26, 1, 'Pérez Zeledón')
INSERT INTO DivisionAdministrativa2 VALUES (27, 1, 'León Cortéz Castro')
INSERT INTO DivisionAdministrativa2 VALUES (28, 2, 'Alajuela')
INSERT INTO DivisionAdministrativa2 VALUES (29, 2, 'San Ramón')
INSERT INTO DivisionAdministrativa2 VALUES (30, 2, 'Grecia')
INSERT INTO DivisionAdministrativa2 VALUES (31, 2, 'San Mateo')
INSERT INTO DivisionAdministrativa2 VALUES (32, 2, 'Atenas')
INSERT INTO DivisionAdministrativa2 VALUES (33, 2, 'Naranjo')
INSERT INTO DivisionAdministrativa2 VALUES (34, 2, 'Palmares')
INSERT INTO DivisionAdministrativa2 VALUES (35, 2, 'Poás')
INSERT INTO DivisionAdministrativa2 VALUES (36, 2, 'Orotina')
INSERT INTO DivisionAdministrativa2 VALUES (37, 2, 'San Carlos')
INSERT INTO DivisionAdministrativa2 VALUES (38, 2, 'Zarcero')
INSERT INTO DivisionAdministrativa2 VALUES (39, 2, 'Valverde Vega')
INSERT INTO DivisionAdministrativa2 VALUES (40, 2, 'Upala')
INSERT INTO DivisionAdministrativa2 VALUES (41, 2, 'Los Chiles')
INSERT INTO DivisionAdministrativa2 VALUES (42, 2, 'Guatuso')
INSERT INTO DivisionAdministrativa2 VALUES (43, 3, 'Cartago')
INSERT INTO DivisionAdministrativa2 VALUES (44, 3, 'Paraíso')
INSERT INTO DivisionAdministrativa2 VALUES (45, 3, 'La Unión')
INSERT INTO DivisionAdministrativa2 VALUES (46, 3, 'Jiménez')
INSERT INTO DivisionAdministrativa2 VALUES (47, 3, 'Turrialba')
INSERT INTO DivisionAdministrativa2 VALUES (48, 3, 'Alvarado')
INSERT INTO DivisionAdministrativa2 VALUES (49, 3, 'Oreamuno')
INSERT INTO DivisionAdministrativa2 VALUES (50, 3, 'El Guarco')
INSERT INTO DivisionAdministrativa2 VALUES (51, 4, 'Heredia')
INSERT INTO DivisionAdministrativa2 VALUES (52, 4, 'Barva')
INSERT INTO DivisionAdministrativa2 VALUES (53, 4, 'Santo Domingo')
INSERT INTO DivisionAdministrativa2 VALUES (54, 4, 'Santa Bárbara')
INSERT INTO DivisionAdministrativa2 VALUES (55, 4, 'San Rafaél')
INSERT INTO DivisionAdministrativa2 VALUES (56, 4, 'San Isidro')
INSERT INTO DivisionAdministrativa2 VALUES (57, 4, 'Belén')
INSERT INTO DivisionAdministrativa2 VALUES (58, 4, 'Flores')
INSERT INTO DivisionAdministrativa2 VALUES (59, 4, 'San Pablo')
INSERT INTO DivisionAdministrativa2 VALUES (60, 4, 'Sarapiquí')
INSERT INTO DivisionAdministrativa2 VALUES (61, 5, 'Liberia')
INSERT INTO DivisionAdministrativa2 VALUES (62, 5, 'Nicoya')
INSERT INTO DivisionAdministrativa2 VALUES (63, 5, 'Santa Cruz')
INSERT INTO DivisionAdministrativa2 VALUES (64, 5, 'Bagaces')
INSERT INTO DivisionAdministrativa2 VALUES (65, 5, 'Carrillo')
INSERT INTO DivisionAdministrativa2 VALUES (66, 5, 'Cañas')
INSERT INTO DivisionAdministrativa2 VALUES (67, 5, 'Abangáres')
INSERT INTO DivisionAdministrativa2 VALUES (68, 5, 'Tilarán')
INSERT INTO DivisionAdministrativa2 VALUES (69, 5, 'Nandayure')
INSERT INTO DivisionAdministrativa2 VALUES (70, 5, 'La Cruz')
INSERT INTO DivisionAdministrativa2 VALUES (71, 5, 'Hojancha')
INSERT INTO DivisionAdministrativa2 VALUES (72, 6, 'Puntarenas')
INSERT INTO DivisionAdministrativa2 VALUES (73, 6, 'Esparza')
INSERT INTO DivisionAdministrativa2 VALUES (74, 6, 'Buenos Aires')
INSERT INTO DivisionAdministrativa2 VALUES (75, 6, 'Montes de Oro')
INSERT INTO DivisionAdministrativa2 VALUES (76, 6, 'Osa')
INSERT INTO DivisionAdministrativa2 VALUES (77, 6, 'Aguirre')
INSERT INTO DivisionAdministrativa2 VALUES (78, 6, 'Golfito')
INSERT INTO DivisionAdministrativa2 VALUES (79, 6, 'Coto Brus')
INSERT INTO DivisionAdministrativa2 VALUES (80, 6, 'Parrita')
INSERT INTO DivisionAdministrativa2 VALUES (81, 6, 'Corredores')
INSERT INTO DivisionAdministrativa2 VALUES (82, 6, 'Garabito')
INSERT INTO DivisionAdministrativa2 VALUES (83, 7, 'Limón')
INSERT INTO DivisionAdministrativa2 VALUES (84, 7, 'Pococí')
INSERT INTO DivisionAdministrativa2 VALUES (85, 7, 'Siquirres')
INSERT INTO DivisionAdministrativa2 VALUES (86, 7, 'Talamanca')
INSERT INTO DivisionAdministrativa2 VALUES (87, 7, 'Matina')
INSERT INTO DivisionAdministrativa2 VALUES (88, 7, 'Guácimo')

INSERT INTO DivisionAdministrativa3 VALUES (89, 8, 'CARMEN')
INSERT INTO DivisionAdministrativa3 VALUES (90, 8, 'MERCED')
INSERT INTO DivisionAdministrativa3 VALUES (91, 8, 'HOSPITAL')
INSERT INTO DivisionAdministrativa3 VALUES (92, 8, 'CATEDRAL')
INSERT INTO DivisionAdministrativa3 VALUES (93, 8, 'ZAPOTE')
INSERT INTO DivisionAdministrativa3 VALUES (94, 8, 'SAN FRANCISCO DE DOS RÍOS')
INSERT INTO DivisionAdministrativa3 VALUES (95, 8, 'URUCA')
INSERT INTO DivisionAdministrativa3 VALUES (96, 8, 'MATA REDONDA')
INSERT INTO DivisionAdministrativa3 VALUES (97, 8, 'PAVAS')
INSERT INTO DivisionAdministrativa3 VALUES (98, 8, 'HATILLO')
INSERT INTO DivisionAdministrativa3 VALUES (99, 8, 'SAN SEBASTIÁN')
INSERT INTO DivisionAdministrativa3 VALUES (100, 9, 'ESCAZÚ')
INSERT INTO DivisionAdministrativa3 VALUES (101, 9, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (102, 9, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (103, 10, 'DESAMPARADOS')
INSERT INTO DivisionAdministrativa3 VALUES (104, 10, 'SAN MIGUEL')
INSERT INTO DivisionAdministrativa3 VALUES (105, 10, 'SAN JUAN DE DIOS')
INSERT INTO DivisionAdministrativa3 VALUES (106, 10, 'SAN RAFAEL ARRIBA')
INSERT INTO DivisionAdministrativa3 VALUES (107, 10, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (108, 10, 'FRAILES')
INSERT INTO DivisionAdministrativa3 VALUES (109, 10, 'PATARRÁ')
INSERT INTO DivisionAdministrativa3 VALUES (110, 10, 'SAN CRISTÓBAL')
INSERT INTO DivisionAdministrativa3 VALUES (111, 10, 'ROSARIO')
INSERT INTO DivisionAdministrativa3 VALUES (112, 10, 'DAMAS')
INSERT INTO DivisionAdministrativa3 VALUES (113, 10, 'SAN RAFAEL ABAJO')
INSERT INTO DivisionAdministrativa3 VALUES (114, 10, 'GRAVILIAS')
INSERT INTO DivisionAdministrativa3 VALUES (115, 10, 'LOS GUIDO')
INSERT INTO DivisionAdministrativa3 VALUES (116, 11, 'SANTIAGO')
INSERT INTO DivisionAdministrativa3 VALUES (117, 11, 'MERCEDES SUR')
INSERT INTO DivisionAdministrativa3 VALUES (118, 11, 'BARBACOAS')
INSERT INTO DivisionAdministrativa3 VALUES (119, 11, 'GRIFO ALTO')
INSERT INTO DivisionAdministrativa3 VALUES (120, 11, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (121, 11, 'CANDELARITA')
INSERT INTO DivisionAdministrativa3 VALUES (122, 11, 'DESAMPARADITOS')
INSERT INTO DivisionAdministrativa3 VALUES (123, 11, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (124, 11, 'CHIRES')
INSERT INTO DivisionAdministrativa3 VALUES (125, 12, 'SAN MARCOS')
INSERT INTO DivisionAdministrativa3 VALUES (126, 12, 'SAN LORENZO')
INSERT INTO DivisionAdministrativa3 VALUES (127, 12, 'SAN CARLOS')
INSERT INTO DivisionAdministrativa3 VALUES (128, 13, 'ASERRI')
INSERT INTO DivisionAdministrativa3 VALUES (129, 13, 'TARBACA')
INSERT INTO DivisionAdministrativa3 VALUES (130, 13, 'VUELTA DE JORCO')
INSERT INTO DivisionAdministrativa3 VALUES (131, 13, 'SAN GABRIEL')
INSERT INTO DivisionAdministrativa3 VALUES (132, 13, 'LEGUA')
INSERT INTO DivisionAdministrativa3 VALUES (133, 13, 'MONTERREY')
INSERT INTO DivisionAdministrativa3 VALUES (134, 13, 'SALITRILLOS')
INSERT INTO DivisionAdministrativa3 VALUES (135, 14, 'COLÓN')
INSERT INTO DivisionAdministrativa3 VALUES (136, 14, 'GUAYABO')
INSERT INTO DivisionAdministrativa3 VALUES (137, 14, 'TABARCIA')
INSERT INTO DivisionAdministrativa3 VALUES (138, 14, 'PIEDRAS NEGRAS')
INSERT INTO DivisionAdministrativa3 VALUES (139, 14, 'PICAGRES')
INSERT INTO DivisionAdministrativa3 VALUES (140, 14, 'JARIS')
INSERT INTO DivisionAdministrativa3 VALUES (141, 14, 'QUITIRRISI')
INSERT INTO DivisionAdministrativa3 VALUES (142, 15, 'GUADALUPE')
INSERT INTO DivisionAdministrativa3 VALUES (143, 15, 'SAN FRANCISCO')
INSERT INTO DivisionAdministrativa3 VALUES (144, 15, 'CALLE BLANCOS')
INSERT INTO DivisionAdministrativa3 VALUES (145, 15, 'MATA DE PLÁTANO')
INSERT INTO DivisionAdministrativa3 VALUES (146, 15, 'IPÍS')
INSERT INTO DivisionAdministrativa3 VALUES (147, 15, 'RANCHO REDONDO')
INSERT INTO DivisionAdministrativa3 VALUES (148, 15, 'PURRAL')
INSERT INTO DivisionAdministrativa3 VALUES (149, 16, 'SANTA ANA')
INSERT INTO DivisionAdministrativa3 VALUES (150, 16, 'SALITRAL')
INSERT INTO DivisionAdministrativa3 VALUES (151, 16, 'POZOS')
INSERT INTO DivisionAdministrativa3 VALUES (152, 16, 'URUCA')
INSERT INTO DivisionAdministrativa3 VALUES (153, 16, 'PIEDADES')
INSERT INTO DivisionAdministrativa3 VALUES (154, 16, 'BRASIL')
INSERT INTO DivisionAdministrativa3 VALUES (155, 17, 'ALAJUELITA')
INSERT INTO DivisionAdministrativa3 VALUES (156, 17, 'SAN JOSECITO')
INSERT INTO DivisionAdministrativa3 VALUES (157, 17, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (158, 17, 'CONCEPCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (159, 17, 'SAN FELIPE')
INSERT INTO DivisionAdministrativa3 VALUES (160, 18, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (161, 18, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (162, 18, 'DULCE NOMBRE DE JESÚS')
INSERT INTO DivisionAdministrativa3 VALUES (163, 18, 'PATALILLO')
INSERT INTO DivisionAdministrativa3 VALUES (164, 18, 'CASCAJAL')
INSERT INTO DivisionAdministrativa3 VALUES (165, 18, 'CASCAJAL')
INSERT INTO DivisionAdministrativa3 VALUES (166, 19, 'SAN IGNACIO')
INSERT INTO DivisionAdministrativa3 VALUES (167, 19, 'GUAITIL Villa')
INSERT INTO DivisionAdministrativa3 VALUES (168, 19, 'PALMICHAL')
INSERT INTO DivisionAdministrativa3 VALUES (169, 19, 'CANGREJAL')
INSERT INTO DivisionAdministrativa3 VALUES (170, 19, 'SABANILLAS')
INSERT INTO DivisionAdministrativa3 VALUES (171, 20, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (172, 20, 'CINCO ESQUINAS')
INSERT INTO DivisionAdministrativa3 VALUES (173, 20, 'ANSELMO LLORENTE')
INSERT INTO DivisionAdministrativa3 VALUES (174, 20, 'LEON XIII')
INSERT INTO DivisionAdministrativa3 VALUES (175, 20, 'COLIMA')
INSERT INTO DivisionAdministrativa3 VALUES (176, 21, 'SAN VICENTE')
INSERT INTO DivisionAdministrativa3 VALUES (177, 21, 'SAN JERÓNIMO')
INSERT INTO DivisionAdministrativa3 VALUES (178, 21, 'LA TRINIDAD')
INSERT INTO DivisionAdministrativa3 VALUES (179, 22, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (180, 22, 'SABANILLA')
INSERT INTO DivisionAdministrativa3 VALUES (181, 22, 'MERCEDES')
INSERT INTO DivisionAdministrativa3 VALUES (182, 22, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (183, 23, 'SAN PABLO')
INSERT INTO DivisionAdministrativa3 VALUES (184, 23, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (185, 23, 'SAN JUAN DE MATA')
INSERT INTO DivisionAdministrativa3 VALUES (186, 23, 'SAN LUIS')
INSERT INTO DivisionAdministrativa3 VALUES (187, 23, 'CARARA')
INSERT INTO DivisionAdministrativa3 VALUES (188, 24, 'SANTA MARÍA')
INSERT INTO DivisionAdministrativa3 VALUES (189, 24, 'JARDÍN')
INSERT INTO DivisionAdministrativa3 VALUES (190, 24, 'COPEY')
INSERT INTO DivisionAdministrativa3 VALUES (191, 25, 'CURRIDABAT')
INSERT INTO DivisionAdministrativa3 VALUES (192, 25, 'GRANADILLA')
INSERT INTO DivisionAdministrativa3 VALUES (193, 25, 'SÁNCHEZ')
INSERT INTO DivisionAdministrativa3 VALUES (194, 25, 'TIRRASES')
INSERT INTO DivisionAdministrativa3 VALUES (195, 26, 'SAN ISIDRO DE EL GENERAL')
INSERT INTO DivisionAdministrativa3 VALUES (196, 26, 'EL GENERAL')
INSERT INTO DivisionAdministrativa3 VALUES (197, 26, 'DANIEL FLORES')
INSERT INTO DivisionAdministrativa3 VALUES (198, 26, 'RIVAS')
INSERT INTO DivisionAdministrativa3 VALUES (199, 26, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (200, 26, 'PLATANARES')
INSERT INTO DivisionAdministrativa3 VALUES (201, 26, 'PEJIBAYE')
INSERT INTO DivisionAdministrativa3 VALUES (202, 26, 'CAJÓN')
INSERT INTO DivisionAdministrativa3 VALUES (203, 26, 'BARÚ')
INSERT INTO DivisionAdministrativa3 VALUES (204, 26, 'RÍO NUEVO')
INSERT INTO DivisionAdministrativa3 VALUES (205, 26, 'PÁRAMO')
INSERT INTO DivisionAdministrativa3 VALUES (206, 27, 'SAN PABLO')
INSERT INTO DivisionAdministrativa3 VALUES (207, 27, 'SAN ANDRÉS')
INSERT INTO DivisionAdministrativa3 VALUES (208, 27, 'LLANO BONITO')
INSERT INTO DivisionAdministrativa3 VALUES (209, 27, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (210, 27, 'SANTA CRUZ')
INSERT INTO DivisionAdministrativa3 VALUES (211, 27, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (212, 28, 'ALAJUELA')
INSERT INTO DivisionAdministrativa3 VALUES (213, 28, 'SAN JOSÉ')
INSERT INTO DivisionAdministrativa3 VALUES (214, 28, 'CARRIZAL')
INSERT INTO DivisionAdministrativa3 VALUES (215, 28, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (216, 28, 'GUÁCIMA')
INSERT INTO DivisionAdministrativa3 VALUES (217, 28, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (218, 28, 'SABANILLA')
INSERT INTO DivisionAdministrativa3 VALUES (219, 28, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (220, 28, 'RÍO SEGUNDO')
INSERT INTO DivisionAdministrativa3 VALUES (221, 28, 'DESAMPARADOS')
INSERT INTO DivisionAdministrativa3 VALUES (222, 28, 'TURRÚCARES')
INSERT INTO DivisionAdministrativa3 VALUES (223, 28, 'TAMBOR')
INSERT INTO DivisionAdministrativa3 VALUES (224, 28, 'GARITA')
INSERT INTO DivisionAdministrativa3 VALUES (225, 28, 'SARAPIQUÍ')
INSERT INTO DivisionAdministrativa3 VALUES (226, 29, 'SAN RAMON')
INSERT INTO DivisionAdministrativa3 VALUES (227, 29, 'SANTIAGO')
INSERT INTO DivisionAdministrativa3 VALUES (228, 29, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (229, 29, 'PIEDADES NORTE')
INSERT INTO DivisionAdministrativa3 VALUES (230, 29, 'PIEDADES SUR')
INSERT INTO DivisionAdministrativa3 VALUES (231, 29, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (232, 29, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (233, 29, 'ÁNGELES')
INSERT INTO DivisionAdministrativa3 VALUES (234, 29, 'ALFARO')
INSERT INTO DivisionAdministrativa3 VALUES (235, 29, 'VOLIO')
INSERT INTO DivisionAdministrativa3 VALUES (236, 29, 'CONCEPCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (237, 29, 'ZAPOTAL')
INSERT INTO DivisionAdministrativa3 VALUES (238, 29, 'PEÑAS BLANCAS')
INSERT INTO DivisionAdministrativa3 VALUES (239, 30, 'GRECIA')
INSERT INTO DivisionAdministrativa3 VALUES (240, 30, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (241, 30, 'SAN JOSÉ')
INSERT INTO DivisionAdministrativa3 VALUES (242, 30, 'SAN ROQUE')
INSERT INTO DivisionAdministrativa3 VALUES (243, 30, 'TACARES')
INSERT INTO DivisionAdministrativa3 VALUES (244, 30, 'RÍO CUARTO')
INSERT INTO DivisionAdministrativa3 VALUES (245, 30, 'PUENTE DE PIEDRA')
INSERT INTO DivisionAdministrativa3 VALUES (246, 30, 'BOLÍVAR')
INSERT INTO DivisionAdministrativa3 VALUES (247, 31, 'SAN MATEO')
INSERT INTO DivisionAdministrativa3 VALUES (248, 31, 'DESMONTE')
INSERT INTO DivisionAdministrativa3 VALUES (249, 31, 'JESÚS MARÍA')
INSERT INTO DivisionAdministrativa3 VALUES (250, 31, 'LABRADOR')
INSERT INTO DivisionAdministrativa3 VALUES (251, 32, 'ATENAS')
INSERT INTO DivisionAdministrativa3 VALUES (252, 32, 'JESÚS')
INSERT INTO DivisionAdministrativa3 VALUES (253, 32, 'MERCEDES')
INSERT INTO DivisionAdministrativa3 VALUES (254, 32, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (255, 32, 'CONCEPCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (256, 32, 'SAN JOSE')
INSERT INTO DivisionAdministrativa3 VALUES (257, 32, 'SANTA EULALIA')
INSERT INTO DivisionAdministrativa3 VALUES (258, 32, 'ESCOBAL')
INSERT INTO DivisionAdministrativa3 VALUES (259, 33, 'NARANJO')
INSERT INTO DivisionAdministrativa3 VALUES (260, 33, 'SAN MIGUEL')
INSERT INTO DivisionAdministrativa3 VALUES (261, 33, 'SAN JOSÉ')
INSERT INTO DivisionAdministrativa3 VALUES (262, 33, 'CIRRÍ SUR')
INSERT INTO DivisionAdministrativa3 VALUES (263, 33, 'SAN JERÓNIMO')
INSERT INTO DivisionAdministrativa3 VALUES (264, 33, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (265, 33, 'EL ROSARIO')
INSERT INTO DivisionAdministrativa3 VALUES (266, 33, 'PALMITOS')
INSERT INTO DivisionAdministrativa3 VALUES (267, 34, 'PALMARES')
INSERT INTO DivisionAdministrativa3 VALUES (268, 34, 'ZARAGOZA')
INSERT INTO DivisionAdministrativa3 VALUES (269, 34, 'BUENOS AIRES')
INSERT INTO DivisionAdministrativa3 VALUES (270, 34, 'SANTIAGO')
INSERT INTO DivisionAdministrativa3 VALUES (271, 34, 'CANDELARIA')
INSERT INTO DivisionAdministrativa3 VALUES (272, 34, 'ESQUÍPULAS')
INSERT INTO DivisionAdministrativa3 VALUES (273, 34, 'LA GRANJA')
INSERT INTO DivisionAdministrativa3 VALUES (274, 35, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (275, 35, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (276, 35, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (277, 35, 'CARRILLOS')
INSERT INTO DivisionAdministrativa3 VALUES (278, 35, 'SABANA REDONDA')
INSERT INTO DivisionAdministrativa3 VALUES (279, 36, 'OROTINA')
INSERT INTO DivisionAdministrativa3 VALUES (280, 36, 'EL MASTATE')
INSERT INTO DivisionAdministrativa3 VALUES (281, 36, 'HACIENDA VIEJA')
INSERT INTO DivisionAdministrativa3 VALUES (282, 36, 'COYOLAR')
INSERT INTO DivisionAdministrativa3 VALUES (283, 36, 'LA CEIBA')
INSERT INTO DivisionAdministrativa3 VALUES (284, 37, 'QUESADA')
INSERT INTO DivisionAdministrativa3 VALUES (285, 37, 'FLORENCIA')
INSERT INTO DivisionAdministrativa3 VALUES (286, 37, 'BUENAVISTA')
INSERT INTO DivisionAdministrativa3 VALUES (287, 37, 'AGUAS ZARCAS')
INSERT INTO DivisionAdministrativa3 VALUES (288, 37, 'VENECIA')
INSERT INTO DivisionAdministrativa3 VALUES (289, 37, 'PITAL')
INSERT INTO DivisionAdministrativa3 VALUES (290, 37, 'LA FORTUNA')
INSERT INTO DivisionAdministrativa3 VALUES (291, 37, 'LA TIGRA')
INSERT INTO DivisionAdministrativa3 VALUES (292, 37, 'LA PALMERA')
INSERT INTO DivisionAdministrativa3 VALUES (293, 37, 'VENADO')
INSERT INTO DivisionAdministrativa3 VALUES (294, 37, 'CUTRIS')
INSERT INTO DivisionAdministrativa3 VALUES (295, 37, 'MONTERREY')
INSERT INTO DivisionAdministrativa3 VALUES (296, 37, 'POCOSOL')
INSERT INTO DivisionAdministrativa3 VALUES (297, 38, 'ZARCERO')
INSERT INTO DivisionAdministrativa3 VALUES (298, 38, 'LAGUNA')
INSERT INTO DivisionAdministrativa3 VALUES (299, 38, 'GUADALUPE')
INSERT INTO DivisionAdministrativa3 VALUES (300, 38, 'PALMIRA')
INSERT INTO DivisionAdministrativa3 VALUES (301, 38, 'ZAPOTE')
INSERT INTO DivisionAdministrativa3 VALUES (302, 38, 'BRISAS')
INSERT INTO DivisionAdministrativa3 VALUES (303, 39, 'SARCHÍ NORTE')
INSERT INTO DivisionAdministrativa3 VALUES (304, 39, 'SARCHÍ SUR')
INSERT INTO DivisionAdministrativa3 VALUES (305, 39, 'TORO AMARILLO')
INSERT INTO DivisionAdministrativa3 VALUES (306, 39, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (307, 39, 'RODRÍGUEZ')
INSERT INTO DivisionAdministrativa3 VALUES (308, 40, 'UPALA')
INSERT INTO DivisionAdministrativa3 VALUES (309, 40, 'AGUAS CLARAS')
INSERT INTO DivisionAdministrativa3 VALUES (310, 40, 'SAN JOSÉ o PIZOTE')
INSERT INTO DivisionAdministrativa3 VALUES (311, 40, 'BIJAGUA')
INSERT INTO DivisionAdministrativa3 VALUES (312, 40, 'DELICIAS')
INSERT INTO DivisionAdministrativa3 VALUES (313, 40, 'DOS RÍOS')
INSERT INTO DivisionAdministrativa3 VALUES (314, 40, 'YOLILLAL')
INSERT INTO DivisionAdministrativa3 VALUES (315, 40, 'CANALETE')
INSERT INTO DivisionAdministrativa3 VALUES (316, 41, 'LOS CHILES')
INSERT INTO DivisionAdministrativa3 VALUES (317, 41, 'CAÑO NEGRO')
INSERT INTO DivisionAdministrativa3 VALUES (318, 41, 'EL AMPARO')
INSERT INTO DivisionAdministrativa3 VALUES (319, 41, 'SAN JORGE')
INSERT INTO DivisionAdministrativa3 VALUES (320, 42, 'BUENAVISTA')
INSERT INTO DivisionAdministrativa3 VALUES (321, 42, 'COTE')
INSERT INTO DivisionAdministrativa3 VALUES (322, 42, 'KATIRA')
INSERT INTO DivisionAdministrativa3 VALUES (323, 43, 'ORIENTAL')
INSERT INTO DivisionAdministrativa3 VALUES (324, 43, 'OCCIDENTAL')
INSERT INTO DivisionAdministrativa3 VALUES (325, 43, 'CARMEN')
INSERT INTO DivisionAdministrativa3 VALUES (326, 43, 'SAN NICOLÁS')
INSERT INTO DivisionAdministrativa3 VALUES (327, 43, 'AGUACALIENTE o SAN FRANCISCO')
INSERT INTO DivisionAdministrativa3 VALUES (328, 43, 'GUADALUPE o ARENILLA')
INSERT INTO DivisionAdministrativa3 VALUES (329, 43, 'CORRALILLO')
INSERT INTO DivisionAdministrativa3 VALUES (330, 43, 'TIERRA BLANCA')
INSERT INTO DivisionAdministrativa3 VALUES (331, 43, 'DULCE NOMBRE')
INSERT INTO DivisionAdministrativa3 VALUES (332, 43, 'LLANO GRANDE')
INSERT INTO DivisionAdministrativa3 VALUES (333, 43, 'QUEBRADILLA')
INSERT INTO DivisionAdministrativa3 VALUES (334, 44, 'PARAÍSO')
INSERT INTO DivisionAdministrativa3 VALUES (335, 44, 'SANTIAGO')
INSERT INTO DivisionAdministrativa3 VALUES (336, 44, 'OROSI')
INSERT INTO DivisionAdministrativa3 VALUES (337, 44, 'CACHÍ')
INSERT INTO DivisionAdministrativa3 VALUES (338, 44, 'LLANOS DE SANTA LUCÍA')
INSERT INTO DivisionAdministrativa3 VALUES (339, 45, 'TRES RÍOS')
INSERT INTO DivisionAdministrativa3 VALUES (340, 45, 'SAN DIEGO')
INSERT INTO DivisionAdministrativa3 VALUES (341, 45, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (342, 45, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (343, 45, 'CONCEPCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (344, 45, 'DULCE NOMBRE')
INSERT INTO DivisionAdministrativa3 VALUES (345, 45, 'SAN RAMÓN')
INSERT INTO DivisionAdministrativa3 VALUES (346, 45, 'RÍO AZUL')
INSERT INTO DivisionAdministrativa3 VALUES (347, 46, 'JUAN VIÑAS')
INSERT INTO DivisionAdministrativa3 VALUES (348, 46, 'TUCURRIQUE')
INSERT INTO DivisionAdministrativa3 VALUES (349, 46, 'PEJIBAYE')
INSERT INTO DivisionAdministrativa3 VALUES (350, 47, 'TURRIALBA')
INSERT INTO DivisionAdministrativa3 VALUES (351, 47, 'LA SUIZA')
INSERT INTO DivisionAdministrativa3 VALUES (352, 47, 'PERALTA')
INSERT INTO DivisionAdministrativa3 VALUES (353, 47, 'SANTA CRUZ')
INSERT INTO DivisionAdministrativa3 VALUES (354, 47, 'SANTA TERESITA')
INSERT INTO DivisionAdministrativa3 VALUES (355, 47, 'PAVONES')
INSERT INTO DivisionAdministrativa3 VALUES (356, 47, 'TUIS')
INSERT INTO DivisionAdministrativa3 VALUES (357, 47, 'TAYUTIC')
INSERT INTO DivisionAdministrativa3 VALUES (358, 47, 'SANTA ROSA')
INSERT INTO DivisionAdministrativa3 VALUES (359, 47, 'TRES EQUIS')
INSERT INTO DivisionAdministrativa3 VALUES (360, 47, 'LA ISABEL')
INSERT INTO DivisionAdministrativa3 VALUES (361, 47, 'CHIRRIPÓ')
INSERT INTO DivisionAdministrativa3 VALUES (362, 48, 'PACAYAS')
INSERT INTO DivisionAdministrativa3 VALUES (363, 48, 'CERVANTES')
INSERT INTO DivisionAdministrativa3 VALUES (364, 48, 'CAPELLADES')
INSERT INTO DivisionAdministrativa3 VALUES (365, 49, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (366, 49, 'COT')
INSERT INTO DivisionAdministrativa3 VALUES (367, 49, 'POTRERO CERRADO')
INSERT INTO DivisionAdministrativa3 VALUES (368, 49, 'CIPRESES')
INSERT INTO DivisionAdministrativa3 VALUES (369, 49, 'SANTA ROSA')
INSERT INTO DivisionAdministrativa3 VALUES (370, 50, 'EL TEJAR')
INSERT INTO DivisionAdministrativa3 VALUES (371, 50, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (372, 50, 'TOBOSI')
INSERT INTO DivisionAdministrativa3 VALUES (373, 50, 'PATIO DE AGUA')
INSERT INTO DivisionAdministrativa3 VALUES (374, 51, 'HEREDIA')
INSERT INTO DivisionAdministrativa3 VALUES (375, 51, 'MERCEDES')
INSERT INTO DivisionAdministrativa3 VALUES (376, 51, 'SAN FRANCISCO')
INSERT INTO DivisionAdministrativa3 VALUES (377, 51, 'ULLOA')
INSERT INTO DivisionAdministrativa3 VALUES (378, 51, 'VARABLANCA')
INSERT INTO DivisionAdministrativa3 VALUES (379, 52, 'BARVA')
INSERT INTO DivisionAdministrativa3 VALUES (380, 52, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (381, 52, 'SAN PABLO')
INSERT INTO DivisionAdministrativa3 VALUES (382, 52, 'SAN ROQUE')
INSERT INTO DivisionAdministrativa3 VALUES (383, 52, 'SANTA LUCÍA')
INSERT INTO DivisionAdministrativa3 VALUES (384, 52, 'SAN JOSÉ DE LA MONTAÑA')
INSERT INTO DivisionAdministrativa3 VALUES (385, 53, 'SAN VICENTE')
INSERT INTO DivisionAdministrativa3 VALUES (386, 53, 'SAN MIGUEL')
INSERT INTO DivisionAdministrativa3 VALUES (387, 53, 'PARACITO')
INSERT INTO DivisionAdministrativa3 VALUES (388, 53, 'SANTO TOMÁS')
INSERT INTO DivisionAdministrativa3 VALUES (389, 53, 'SANTA ROSA')
INSERT INTO DivisionAdministrativa3 VALUES (390, 53, 'TURES')
INSERT INTO DivisionAdministrativa3 VALUES (391, 53, 'PARÁ')
INSERT INTO DivisionAdministrativa3 VALUES (392, 54, 'SANTA BÁRBARA')
INSERT INTO DivisionAdministrativa3 VALUES (393, 54, 'SAN PEDRO')
INSERT INTO DivisionAdministrativa3 VALUES (394, 54, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (395, 54, 'JESÚS')
INSERT INTO DivisionAdministrativa3 VALUES (396, 54, 'SANTO DOMINGO')
INSERT INTO DivisionAdministrativa3 VALUES (397, 54, 'PURABÁ')
INSERT INTO DivisionAdministrativa3 VALUES (398, 55, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (399, 55, 'SAN JOSECITO')
INSERT INTO DivisionAdministrativa3 VALUES (400, 55, 'SANTIAGO')
INSERT INTO DivisionAdministrativa3 VALUES (401, 55, 'ÁNGELES')
INSERT INTO DivisionAdministrativa3 VALUES (402, 55, 'CONCEPCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (403, 56, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (404, 56, 'SAN JOSÉ')
INSERT INTO DivisionAdministrativa3 VALUES (405, 56, 'CONCEPCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (406, 56, 'SAN FRANCISCO')
INSERT INTO DivisionAdministrativa3 VALUES (407, 57, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (408, 57, 'LA RIBERA')
INSERT INTO DivisionAdministrativa3 VALUES (409, 57, 'LA ASUNCIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (410, 58, 'SAN JOAQUÍN')
INSERT INTO DivisionAdministrativa3 VALUES (411, 58, 'BARRANTES')
INSERT INTO DivisionAdministrativa3 VALUES (412, 58, 'LLORENTE')
INSERT INTO DivisionAdministrativa3 VALUES (413, 59, 'SAN PABLO')
INSERT INTO DivisionAdministrativa3 VALUES (414, 60, 'PUERTO VIEJO')
INSERT INTO DivisionAdministrativa3 VALUES (415, 60, 'LA VIRGEN')
INSERT INTO DivisionAdministrativa3 VALUES (416, 60, 'LAS HORQUETAS')
INSERT INTO DivisionAdministrativa3 VALUES (417, 60, 'LLANURAS DEL GASPAR')
INSERT INTO DivisionAdministrativa3 VALUES (418, 60, 'CUREÑA')
INSERT INTO DivisionAdministrativa3 VALUES (419, 61, 'LIBERIA')
INSERT INTO DivisionAdministrativa3 VALUES (420, 61, 'CAÑAS DULCES')
INSERT INTO DivisionAdministrativa3 VALUES (421, 61, 'MAYORGA')
INSERT INTO DivisionAdministrativa3 VALUES (422, 61, 'NACASCOLO')
INSERT INTO DivisionAdministrativa3 VALUES (423, 61, 'CURUBANDÉ')
INSERT INTO DivisionAdministrativa3 VALUES (424, 62, 'NICOYA')
INSERT INTO DivisionAdministrativa3 VALUES (425, 62, 'MANSIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (426, 62, 'SAN ANTONIO')
INSERT INTO DivisionAdministrativa3 VALUES (427, 62, 'QUEBRADA HONDA')
INSERT INTO DivisionAdministrativa3 VALUES (428, 62, 'SÁMARA')
INSERT INTO DivisionAdministrativa3 VALUES (429, 62, 'NOSARA')
INSERT INTO DivisionAdministrativa3 VALUES (430, 62, 'BELÉN DE NOSARITA')
INSERT INTO DivisionAdministrativa3 VALUES (431, 63, 'SANTA CRUZ')
INSERT INTO DivisionAdministrativa3 VALUES (432, 63, 'BOLSÓN')
INSERT INTO DivisionAdministrativa3 VALUES (433, 63, 'VEINTISIETE DE ABRIL')
INSERT INTO DivisionAdministrativa3 VALUES (434, 63, 'TEMPATE')
INSERT INTO DivisionAdministrativa3 VALUES (435, 63, 'CARTAGENA')
INSERT INTO DivisionAdministrativa3 VALUES (436, 63, 'CUAJINIQUIL')
INSERT INTO DivisionAdministrativa3 VALUES (437, 63, 'DIRIÁ')
INSERT INTO DivisionAdministrativa3 VALUES (438, 63, 'CABO VELAS')
INSERT INTO DivisionAdministrativa3 VALUES (439, 63, 'TAMARINDO')
INSERT INTO DivisionAdministrativa3 VALUES (440, 64, 'BAGACES')
INSERT INTO DivisionAdministrativa3 VALUES (441, 64, 'LA FORTUNA')
INSERT INTO DivisionAdministrativa3 VALUES (442, 64, 'MOGOTE')
INSERT INTO DivisionAdministrativa3 VALUES (443, 64, 'RÍO NARANJO')
INSERT INTO DivisionAdministrativa3 VALUES (444, 65, 'FILADELFIA')
INSERT INTO DivisionAdministrativa3 VALUES (445, 65, 'PALMIRA')
INSERT INTO DivisionAdministrativa3 VALUES (446, 65, 'SARDINAL')
INSERT INTO DivisionAdministrativa3 VALUES (447, 65, 'BELÉN')
INSERT INTO DivisionAdministrativa3 VALUES (448, 66, 'CAÑAS')
INSERT INTO DivisionAdministrativa3 VALUES (449, 66, 'PALMIRA')
INSERT INTO DivisionAdministrativa3 VALUES (450, 66, 'SAN MIGUEL')
INSERT INTO DivisionAdministrativa3 VALUES (451, 66, 'BEBEDERO')
INSERT INTO DivisionAdministrativa3 VALUES (452, 66, 'POROZAL')
INSERT INTO DivisionAdministrativa3 VALUES (453, 67, 'LAS JUNTAS')
INSERT INTO DivisionAdministrativa3 VALUES (454, 67, 'SIERRA')
INSERT INTO DivisionAdministrativa3 VALUES (455, 67, 'SAN JUAN')
INSERT INTO DivisionAdministrativa3 VALUES (456, 67, 'COLORADO')
INSERT INTO DivisionAdministrativa3 VALUES (457, 68, 'TILARÁN')
INSERT INTO DivisionAdministrativa3 VALUES (458, 68, 'QUEBRADA GRANDE')
INSERT INTO DivisionAdministrativa3 VALUES (459, 68, 'TRONADORA')
INSERT INTO DivisionAdministrativa3 VALUES (460, 68, 'SANTA ROSA')
INSERT INTO DivisionAdministrativa3 VALUES (461, 68, 'LÍBANO')
INSERT INTO DivisionAdministrativa3 VALUES (462, 68, 'TIERRAS MORENAS')
INSERT INTO DivisionAdministrativa3 VALUES (463, 68, 'ARENAL')
INSERT INTO DivisionAdministrativa3 VALUES (464, 69, 'CARMONA')
INSERT INTO DivisionAdministrativa3 VALUES (465, 69, 'SANTA RITA')
INSERT INTO DivisionAdministrativa3 VALUES (466, 69, 'ZAPOTAL')
INSERT INTO DivisionAdministrativa3 VALUES (467, 69, 'SAN PABLO')
INSERT INTO DivisionAdministrativa3 VALUES (468, 69, 'PORVENIR')
INSERT INTO DivisionAdministrativa3 VALUES (469, 69, 'BEJUCO')
INSERT INTO DivisionAdministrativa3 VALUES (470, 70, 'LA CRUZ')
INSERT INTO DivisionAdministrativa3 VALUES (471, 70, 'SANTA CECILIA')
INSERT INTO DivisionAdministrativa3 VALUES (472, 70, 'LA GARITA')
INSERT INTO DivisionAdministrativa3 VALUES (473, 70, 'SANTA ELENA')
INSERT INTO DivisionAdministrativa3 VALUES (474, 71, 'HOJANCHA')
INSERT INTO DivisionAdministrativa3 VALUES (475, 71, 'MONTE ROMO')
INSERT INTO DivisionAdministrativa3 VALUES (476, 71, 'PUERTO CARRILLO')
INSERT INTO DivisionAdministrativa3 VALUES (477, 71, 'HUACAS')
INSERT INTO DivisionAdministrativa3 VALUES (478, 72, 'PUNTARENAS')
INSERT INTO DivisionAdministrativa3 VALUES (479, 72, 'PITAHAYA')
INSERT INTO DivisionAdministrativa3 VALUES (480, 72, 'CHOMES')
INSERT INTO DivisionAdministrativa3 VALUES (481, 72, 'LEPANTO')
INSERT INTO DivisionAdministrativa3 VALUES (482, 72, 'PAQUERA')
INSERT INTO DivisionAdministrativa3 VALUES (483, 72, 'MANZANILLO')
INSERT INTO DivisionAdministrativa3 VALUES (484, 72, 'GUACIMAL')
INSERT INTO DivisionAdministrativa3 VALUES (485, 72, 'BARRANCA')
INSERT INTO DivisionAdministrativa3 VALUES (486, 72, 'MONTE VERDE')
INSERT INTO DivisionAdministrativa3 VALUES (487, 72, 'CÓBANO')
INSERT INTO DivisionAdministrativa3 VALUES (488, 72, 'CHACARITA')
INSERT INTO DivisionAdministrativa3 VALUES (489, 72, 'CHIRA')
INSERT INTO DivisionAdministrativa3 VALUES (490, 72, 'ACAPULCO')
INSERT INTO DivisionAdministrativa3 VALUES (491, 72, 'EL ROBLE')
INSERT INTO DivisionAdministrativa3 VALUES (492, 72, 'ARANCIBIA')
INSERT INTO DivisionAdministrativa3 VALUES (493, 73, 'ESPÍRITU SANTO')
INSERT INTO DivisionAdministrativa3 VALUES (494, 73, 'SAN JUAN GRANDE')
INSERT INTO DivisionAdministrativa3 VALUES (495, 73, 'MACACONA')
INSERT INTO DivisionAdministrativa3 VALUES (496, 73, 'SAN RAFAEL')
INSERT INTO DivisionAdministrativa3 VALUES (497, 73, 'SAN JERÓNIMO')
INSERT INTO DivisionAdministrativa3 VALUES (498, 73, 'CALDERA')
INSERT INTO DivisionAdministrativa3 VALUES (499, 74, 'BUENOS AIRES')
INSERT INTO DivisionAdministrativa3 VALUES (500, 74, 'VOLCÁN')
INSERT INTO DivisionAdministrativa3 VALUES (501, 74, 'POTRERO GRANDE')
INSERT INTO DivisionAdministrativa3 VALUES (502, 74, 'BORUCA')
INSERT INTO DivisionAdministrativa3 VALUES (503, 74, 'PILAS')
INSERT INTO DivisionAdministrativa3 VALUES (504, 74, 'COLINAS')
INSERT INTO DivisionAdministrativa3 VALUES (505, 74, 'CHÁNGUENA')
INSERT INTO DivisionAdministrativa3 VALUES (506, 74, 'BIOLLEY')
INSERT INTO DivisionAdministrativa3 VALUES (507, 74, 'BRUNKA')
INSERT INTO DivisionAdministrativa3 VALUES (508, 75, 'MIRAMAR')
INSERT INTO DivisionAdministrativa3 VALUES (509, 75, 'LA UNIÓN')
INSERT INTO DivisionAdministrativa3 VALUES (510, 75, 'SAN ISIDRO')
INSERT INTO DivisionAdministrativa3 VALUES (511, 76, 'PUERTO CORTÉS')
INSERT INTO DivisionAdministrativa3 VALUES (512, 76, 'PALMAR')
INSERT INTO DivisionAdministrativa3 VALUES (513, 76, 'SIERPE')
INSERT INTO DivisionAdministrativa3 VALUES (514, 76, 'BAHÍA BALLENA')
INSERT INTO DivisionAdministrativa3 VALUES (515, 76, 'PIEDRAS BLANCAS')
INSERT INTO DivisionAdministrativa3 VALUES (516, 76, 'BAHÍA DRAKE')
INSERT INTO DivisionAdministrativa3 VALUES (517, 77, 'QUEPOS')
INSERT INTO DivisionAdministrativa3 VALUES (518, 77, 'SAVEGRE')
INSERT INTO DivisionAdministrativa3 VALUES (519, 77, 'NARANJITO')
INSERT INTO DivisionAdministrativa3 VALUES (520, 78, 'GOLFITO')
INSERT INTO DivisionAdministrativa3 VALUES (521, 78, 'PUERTO JIMÉNEZ')
INSERT INTO DivisionAdministrativa3 VALUES (522, 78, 'GUAYCARÁ')
INSERT INTO DivisionAdministrativa3 VALUES (523, 78, 'PAVÓN')
INSERT INTO DivisionAdministrativa3 VALUES (524, 79, 'SAN VITO')
INSERT INTO DivisionAdministrativa3 VALUES (525, 79, 'SABALITO')
INSERT INTO DivisionAdministrativa3 VALUES (526, 79, 'AGUABUENA')
INSERT INTO DivisionAdministrativa3 VALUES (527, 79, 'LIMONCITO')
INSERT INTO DivisionAdministrativa3 VALUES (528, 79, 'PITTIER')
INSERT INTO DivisionAdministrativa3 VALUES (529, 79, 'GUTIERREZ BRAUN')
INSERT INTO DivisionAdministrativa3 VALUES (530, 80, 'PARRITA')
INSERT INTO DivisionAdministrativa3 VALUES (531, 81, 'CORREDOR')
INSERT INTO DivisionAdministrativa3 VALUES (532, 81, 'LA CUESTA')
INSERT INTO DivisionAdministrativa3 VALUES (533, 81, 'CANOAS')
INSERT INTO DivisionAdministrativa3 VALUES (534, 81, 'LAUREL')
INSERT INTO DivisionAdministrativa3 VALUES (535, 82, 'JACÓ')
INSERT INTO DivisionAdministrativa3 VALUES (536, 82, 'TÁRCOLES')
INSERT INTO DivisionAdministrativa3 VALUES (537, 83, 'LIMÓN')
INSERT INTO DivisionAdministrativa3 VALUES (538, 83, 'VALLE LA ESTRELLA')
INSERT INTO DivisionAdministrativa3 VALUES (539, 83, 'MATAMA')
INSERT INTO DivisionAdministrativa3 VALUES (540, 84, 'GUÁPILES')
INSERT INTO DivisionAdministrativa3 VALUES (541, 84, 'JIMÉNEZ')
INSERT INTO DivisionAdministrativa3 VALUES (542, 84, 'RITA')
INSERT INTO DivisionAdministrativa3 VALUES (543, 84, 'ROXANA')
INSERT INTO DivisionAdministrativa3 VALUES (544, 84, 'CARIARI')
INSERT INTO DivisionAdministrativa3 VALUES (545, 84, 'COLORADO')
INSERT INTO DivisionAdministrativa3 VALUES (546, 84, 'LA COLONIA')
INSERT INTO DivisionAdministrativa3 VALUES (547, 85, 'SIQUIRRES')
INSERT INTO DivisionAdministrativa3 VALUES (548, 85, 'PACUARITO')
INSERT INTO DivisionAdministrativa3 VALUES (549, 85, 'FLORIDA')
INSERT INTO DivisionAdministrativa3 VALUES (550, 85, 'GERMANIA')
INSERT INTO DivisionAdministrativa3 VALUES (551, 85, 'EL CAIRO')
INSERT INTO DivisionAdministrativa3 VALUES (552, 85, 'ALEGRÍA')
INSERT INTO DivisionAdministrativa3 VALUES (553, 86, 'BRATSI')
INSERT INTO DivisionAdministrativa3 VALUES (554, 86, 'SIXAOLA')
INSERT INTO DivisionAdministrativa3 VALUES (555, 86, 'CAHUITA')
INSERT INTO DivisionAdministrativa3 VALUES (556, 86, 'TELIRE')
INSERT INTO DivisionAdministrativa3 VALUES (557, 87, 'MATINA')
INSERT INTO DivisionAdministrativa3 VALUES (558, 87, 'BATÁN')
INSERT INTO DivisionAdministrativa3 VALUES (559, 87, 'CARRANDI')
INSERT INTO DivisionAdministrativa3 VALUES (560, 88, 'GUÁCIMO')
INSERT INTO DivisionAdministrativa3 VALUES (561, 88, 'MERCEDES')
INSERT INTO DivisionAdministrativa3 VALUES (562, 88, 'POCORA')
INSERT INTO DivisionAdministrativa3 VALUES (563, 88, 'RÍO JIMÉNEZ')
INSERT INTO DivisionAdministrativa3 VALUES (564, 88, 'DUACARÍ')