  SELECT * FROM ProductorAbejasNativasVisitaIndividual
  SELECT * FROM ProductorAbejasNativasVisitaIndividualAccionCorrectivaObligatoria
  SELECT * FROM ProductorAbejasNativasVisitaIndividualColmenasEnCaja
  SELECT * FROM ProductorAbejasNativasVisitaIndividualColmenasEnTrampa