  SELECT * FROM AbejasNativasVisitaGrupal
  SELECT * FROM AbejasNativasVisitaGrupalParticipante
  SELECT * FROM Meliponario
  SELECT * FROM MeliponarioCaja
  SELECT * FROM MeliponarioCajaAccion
  SELECT * FROM MeliponarioCajaHistorial
  SELECT * FROM MeliponarioCosecha
  SELECT * FROM MeliponarioCosechaDetalle
  SELECT * FROM MeliponarioCosechaDetalleCaja
  SELECT * FROM Productor
  SELECT * FROM ProductorAbejasNativasMaterialEntregado
  SELECT * FROM ProductorAbejasNativasVisitaIndividual
  SELECT * FROM ProductorAbejasNativasVisitaIndividualAccionCorrectivaObligatoria
  SELECT * FROM ProductorAbejasNativasVisitaIndividualColmenasEnCaja
  SELECT * FROM ProductorAbejasNativasVisitaIndividualColmenasEnTrampa
  SELECT * FROM ProductorContacto
  SELECT * FROM ProductorDetalleProduccionAnimal
  SELECT * FROM ProductorDetalleProduccionVegetal
  SELECT * FROM ProductorDocumentoEntregado
  SELECT * FROM ProductorInventarioEspecies
  SELECT * FROM ProductorMiembroHogar
  SELECT * FROM ProductorProyecto